GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "New",
    "number": "0101"
}

###
PUT http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "New",
    "number": "9999"
}

###
DELETE http://localhost:3001/api/persons/93