GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Sayanta",
    "number": "01010101"
}

###
PUT http://localhost:3001/api/persons/1
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "99999999"
}

###
DELETE http://localhost:3001/api/persons/2